version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    platform: linux/arm64/v8
    ports:
      - "27017:27017"
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672